"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { Plus } from "lucide-react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { z } from "zod";
import { ManagerRoute } from "@/components/auth/manager-route";
import { EmptyState, ErrorState, LoadingState } from "@/components/shared/async-state";
import { PageHeader } from "@/components/shared/page-header";
import { PaginationControls } from "@/components/shared/pagination-controls";
import { ActiveBadge, RoleBadge } from "@/components/shared/status-badges";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { apiFetch, ApiError, queryString } from "@/lib/api/client";
import type { Page, User } from "@/lib/api/types";
import { useApiQuery } from "@/lib/hooks/use-api-query";
const schema=z.object({email:z.string().email(),full_name:z.string().min(1),password:z.string(),role:z.enum(["manager","employee"]),is_active:z.boolean()});type Values=z.infer<typeof schema>;
export default function UsersPage(){return <ManagerRoute><Users/></ManagerRoute>}
function Users(){const[page,setPage]=useState(1),[search,setSearch]=useState(""),[role,setRole]=useState("all"),[active,setActive]=useState("all");const[editing,setEditing]=useState<User|null|undefined>();const path=`/users${queryString({page,page_size:20,search:search||null,role:role==="all"?null:role,is_active:active==="all"?null:active})}`;const q=useApiQuery<Page<User>>(path);return <><PageHeader title="Users" description="Manage employee access and manager permissions." actions={<Button onClick={()=>setEditing(null)}><Plus/>Add user</Button>}/><Card className="mb-5"><CardContent className="grid gap-3 p-4 sm:grid-cols-3"><Input aria-label="Search by email" placeholder="Search by email" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&q.reload()}/><Filter value={role} set={setRole} items={[["all","All roles"],["manager","Manager"],["employee","Employee"]]}/><Filter value={active} set={setActive} items={[["all","All statuses"],["true","Active"],["false","Inactive"]]}/></CardContent></Card>{q.loading?<LoadingState/>:q.error?<ErrorState message={q.error.message} retry={q.reload}/>:!q.data?.items.length?<EmptyState title="No users found" description="Adjust your filters or create a user."/>:<><div className="overflow-hidden rounded-xl border bg-white"><div className="divide-y">{q.data.items.map(u=><div key={u.id} className="flex flex-col justify-between gap-3 p-4 sm:flex-row sm:items-center"><div><p className="font-medium">{u.full_name}</p><p className="text-sm text-slate-600">{u.email}</p></div><div className="flex items-center gap-2"><RoleBadge role={u.role}/><ActiveBadge active={u.is_active}/><Button variant="outline" size="sm" onClick={()=>setEditing(u)}>Edit</Button></div></div>)}</div></div><PaginationControls page={q.data.page} pages={q.data.pages} total={q.data.total} onPageChange={n=>{setPage(n);q.reload(`/users${queryString({page:n,page_size:20})}`)}}/></>}<UserDialog user={editing} close={()=>setEditing(undefined)} saved={()=>{setEditing(undefined);q.reload()}}/></>}
function Filter({value,set,items}:{value:string;set:(v:string)=>void;items:string[][]}){return <Select value={value} onValueChange={v=>set(v??"all")}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i[0]} value={i[0]}>{i[1]}</SelectItem>)}</SelectContent></Select>}
function UserDialog({user,close,saved}:{user:User|null|undefined;close:()=>void;saved:()=>void}){const form=useForm<Values>({resolver:zodResolver(schema),values:{email:user?.email??"",full_name:user?.full_name??"",password:"",role:user?.role??"employee",is_active:user?.is_active??true}});async function submit(v:Values){if(!user&&v.password.length<8){form.setError("password",{message:"Use at least 8 characters"});return}if(user&&v.password&&v.password.length<8){form.setError("password",{message:"Use at least 8 characters"});return}const body=user?{role:v.role,is_active:v.is_active,...(v.password?{password:v.password}:{})}:v;try{await apiFetch(user?`/users/${user.id}`:"/users",{method:user?"PATCH":"POST",body});toast.success(user?"User updated":"User created");saved()}catch(e){form.setError("root",{message:e instanceof ApiError?e.message:"Unable to save user"})}}return <Dialog open={user!==undefined} onOpenChange={v=>!v&&close()}><DialogContent><DialogHeader><DialogTitle>{user?"Edit user":"Create user"}</DialogTitle><DialogDescription>{user?"Role and status changes take effect immediately.":"Create credentials for a team member."}</DialogDescription></DialogHeader><form onSubmit={form.handleSubmit(submit)} className="space-y-4">{!user&&<><Field label="Full name" error={form.formState.errors.full_name?.message}><Input {...form.register("full_name")}/></Field><Field label="Email" error={form.formState.errors.email?.message}><Input {...form.register("email")} type="email"/></Field></>}<Field label={user?"New password (optional)":"Password"} error={form.formState.errors.password?.message}><Input {...form.register("password")} type="password"/></Field><Field label="Role"><select className="h-10 w-full rounded-md border px-3" {...form.register("role")}><option value="employee">Employee</option><option value="manager">Manager</option></select></Field>{user&&<label className="flex items-center gap-2"><input type="checkbox" {...form.register("is_active")}/> Active account</label>}{form.formState.errors.root&&<p role="alert" className="text-sm text-red-700">{form.formState.errors.root.message}</p>}<DialogFooter><Button type="button" variant="outline" onClick={close}>Cancel</Button><Button type="submit">Save</Button></DialogFooter></form></DialogContent></Dialog>}
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <div className="space-y-1"><Label>{label}</Label>{children}{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}</div>}
