"use client";
import { Clipboard, ExternalLink } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { toast } from "sonner";
import { EmptyState, ErrorState, LoadingState } from "@/components/shared/async-state";
import { PageHeader } from "@/components/shared/page-header";
import { PaginationControls } from "@/components/shared/pagination-controls";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { queryString } from "@/lib/api/client";
import type { Category, LowStockItem, Page, Vendor } from "@/lib/api/types";
import { formatDate } from "@/lib/format";
import { useApiQuery } from "@/lib/hooks/use-api-query";
export default function LowStockPage(){const[page,setPage]=useState(1),[category,setCategory]=useState("all"),[vendor,setVendor]=useState("all");const path=`/alerts/low-stock${queryString({page,page_size:20,category_id:category==="all"?null:category,preferred_vendor_id:vendor==="all"?null:vendor})}`;const q=useApiQuery<Page<LowStockItem>>(path);const categories=useApiQuery<Page<Category>>("/categories?page_size=100&is_active=true");const vendors=useApiQuery<Page<Vendor>>("/vendors?page_size=100&is_active=true");async function copy(){if(!q.data)return;await navigator.clipboard.writeText(q.data.items.map(i=>`${i.sku} — ${i.name}: reorder ${i.recommended_reorder_quantity}`).join("\n"));toast.success("Reorder summary copied")};return <><PageHeader title="Low stock" description="Counted products below their minimum, prioritized by the backend." actions={q.data?.items.length?<Button variant="outline" onClick={copy}><Clipboard/>Copy reorder summary</Button>:undefined}/><Card className="mb-5"><CardContent className="grid gap-4 p-4 sm:grid-cols-2"><Filter label="Category" value={category} set={v=>{setCategory(v);setPage(1)}} rows={categories.data?.items??[]}/><Filter label="Preferred vendor" value={vendor} set={v=>{setVendor(v);setPage(1)}} rows={vendors.data?.items??[]}/></CardContent></Card><p className="mb-4 text-sm text-slate-600">Uncounted products are excluded because no official submitted quantity exists yet.</p>{q.loading?<LoadingState/>:q.error?<ErrorState message={q.error.message} retry={q.reload}/>:!q.data?.items.length?<EmptyState title="No low-stock products" description="All counted products meet their minimum levels for these filters."/>:<><div className="grid gap-3">{q.data.items.map(i=><Card key={i.product_id}><CardContent className="grid gap-4 p-5 sm:grid-cols-[2fr_repeat(3,1fr)_auto] sm:items-center"><div><Link href={`/products/${i.product_id}`} className="font-semibold hover:underline">{i.name} <ExternalLink className="inline size-3"/></Link><p className="text-sm text-slate-600">{i.sku} · {i.category.name} · {i.preferred_vendor?.name??"No vendor"}</p><p className="text-xs text-slate-500">Counted {formatDate(i.latest_count_at)}</p></div><Stat label="On hand" value={i.latest_quantity}/><Stat label="Minimum / target" value={`${i.minimum_quantity} / ${i.target_quantity}`}/><Stat label="Reorder" value={i.recommended_reorder_quantity}/><div className="rounded-full bg-red-100 px-3 py-1 text-sm font-medium text-red-800">Low stock</div></CardContent></Card>)}</div><PaginationControls page={q.data.page} pages={q.data.pages} total={q.data.total} onPageChange={n=>{setPage(n);q.reload(`/alerts/low-stock${queryString({page:n,page_size:20})}`)}}/></>}</>}
function Filter({label,value,set,rows}:{label:string;value:string;set:(v:string)=>void;rows:{id:string;name:string}[]}){return <div><Label>{label}</Label><Select value={value} onValueChange={v=>set(v??"all")}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All</SelectItem>{rows.map(r=><SelectItem key={r.id} value={r.id}>{r.name}</SelectItem>)}</SelectContent></Select></div>}
function Stat({label,value}:{label:string;value:React.ReactNode}){return <div><p className="text-xs text-slate-500">{label}</p><p className="font-semibold">{value}</p></div>}
