"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useAuth } from "@/components/auth/auth-provider";
import { ErrorState, LoadingState } from "@/components/shared/async-state";
import { PageHeader } from "@/components/shared/page-header";
import { PaginationControls } from "@/components/shared/pagination-controls";
import { ActiveBadge, StockBadge } from "@/components/shared/status-badges";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import type { Page, Product, ProductHistoryItem } from "@/lib/api/types";
import { formatDate } from "@/lib/format";
import { useApiQuery } from "@/lib/hooks/use-api-query";
export default function ProductDetailPage(){const{id}=useParams<{id:string}>();const{user}=useAuth();const product=useApiQuery<Product>(`/products/${id}`);const history=useApiQuery<Page<ProductHistoryItem>>(`/products/${id}/count-history?page=1&page_size=10`);if(product.loading)return <LoadingState/>;if(product.error||!product.data)return <ErrorState message={product.error?.message??"Product not found"}/>;const p=product.data;return <><PageHeader title={p.name} description={`${p.sku} · ${p.category.name}`} actions={user?.role==="manager"?<Button render={<Link href={`/products/${id}/edit`}/>}>Edit product</Button>:undefined}/><div className="grid gap-5 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader><CardTitle>Inventory status</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Datum label="Latest quantity" value={p.latest_quantity??"Uncounted"}/><Datum label="Last counted" value={p.latest_count_at?formatDate(p.latest_count_at):"Never"}/><Datum label="Minimum / target" value={`${p.minimum_quantity} / ${p.target_quantity}`}/><Datum label="Recommended reorder" value={p.recommended_reorder_quantity??"Not available"}/><div className="flex gap-2"><StockBadge counted={p.is_counted} low={p.is_low_stock}/><ActiveBadge active={p.is_active}/></div>{!p.is_counted&&<p className="text-sm text-slate-600 sm:col-span-2">This product is uncounted. It is not treated as zero or included in low-stock alerts until a submitted count records it.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Catalog details</CardTitle></CardHeader><CardContent className="space-y-4"><Datum label="Vendor" value={p.preferred_vendor?.name??"None"}/><Datum label="Unit" value={p.unit_description??"Not specified"}/><Datum label="Description" value={p.description??"No description"}/></CardContent></Card></div><Card className="mt-5"><CardHeader><CardTitle>Submitted count history</CardTitle></CardHeader><CardContent>{history.loading?<LoadingState/>:history.error?<ErrorState message={history.error.message} retry={history.reload}/>:!history.data?.items.length?<p className="text-sm text-slate-600">No submitted counts yet.</p>:<><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Submitted by</TableHead><TableHead className="text-right">Quantity</TableHead></TableRow></TableHeader><TableBody>{history.data.items.map(row=><TableRow key={row.count_id}><TableCell><Link className="hover:underline" href={`/inventory-counts/${row.count_id}`}>{formatDate(row.submitted_at)}</Link></TableCell><TableCell>{row.submitted_by_email}</TableCell><TableCell className="text-right font-medium">{row.quantity}</TableCell></TableRow>)}</TableBody></Table><PaginationControls page={history.data.page} pages={history.data.pages} total={history.data.total} onPageChange={next=>history.reload(`/products/${id}/count-history?page=${next}&page_size=10`)}/></>}</CardContent></Card></>}
function Datum({label,value}:{label:string;value:React.ReactNode}){return <div><p className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</p><div className="mt-1 font-medium">{value}</div></div>}
